# Generated by Django 4.0.5 on 2022-07-04 18:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_sent', models.FloatField()),
                ('sent_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactapp.user')),
                ('sent_to', models.ManyToManyField(related_name='sent_to', to='transactapp.user')),
            ],
        ),
    ]
